### ISSUE TITLE
Explain bonus ids

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/AzerothAuctionAssassin#138]
New wiki

**Comment by RealPrivateScriptL9** [comment]
@CodeRabbit Explain exactly line by line how to use it.

**Comment by RealPrivateScriptL9** [comment]
@CodeRabbit how do I even know about the item bonus ids? I only have a normal id like 225723, what am I supposed to do with it? Can you explain it in pseudo-code or just word by word how would one do it?
