### ISSUE TITLE
Season of Discovery server support 

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/AzerothAuctionAssassin#7]
so theres no api for SoD yet, when they add it we can support that server group too

ahh bummer. Didn't realize that. I make little bots/api stuff in the past and have one for realm status, and saw it had an api endpoint for auctions listed, but I guess they didn't actually populate it
```
_links     : @{self=}
id         : 5816
has_queue  : False
status     : @{type=UP; name=Up}
population : @{type=HIGH; name=High}
realms     : {@{id=5816; region=; connected_realm=; name=Crusader Strike; category=Seasonal; locale=enUS; timezone=America/Denver; type=; is_tournament=False; slug=crusader-strike}}
auctions   : @{href=https://us.api.blizzard.com/data/wow/connected-realm/5816/auctions/?namespace=dynamic-classic1x-us}
pvp_season : @{href=https://us.api.blizzard.com/data/wow/pvp-region/2/pvp-season/?namespace=dynamic-classic1x-us}
```
but then quering the api for auctions does give a 404, so I guess not possible for now

**Comment by ninthwalker** [comment]
Additional info:

Classic servers have an additional index for AH data since their AH's are not combined


2 = Alliance
6 = Horde AH
7 = Nuetral AH

iEndpoint Example for Horde AH data on Crusader Strike server:
https://us.api.blizzard.com/data/wow/connected-realm/5816/auctions/6?namespace=dynamic-classic1x-us&locale=en_US&access_token=$token

**Comment by ninthwalker** [comment]
Here are the realm slug/ID's for the 8 US servers. I didn't Query/check for EU ones.

crusader-strike: 5816
chaos-bolt: 5820
living-flame: 5815
lone-wolf: 5814
lava-lash: 5819
wild-growth: 5813
penance-au: 5817
shadowstrike-au: 5818
